### ISSUE TITLE
[Bug] Partial Recon fails with "ImportError: cannot import name 'Neo4jClient' from 'graph_db'" on v6.9.0

### ISSUE THREAD

**Issue by sk21-art** [samugit83/redamon#169]
### Component

other

### Describe the Bug
After upgrading from v6.8.0 to v6.9.0 (primarily for the improved RAM memory governor), the Partial Recon pipeline consistently fails to start. It crashes immediately with an `ImportError` related to `Neo4jClient`. Full recon or other services seem unaffected, but partial recon is completely blocked.

### Environment
- **OS**: Ubuntu 24.04 / WSL2 (8GB RAM)
- **RedAmon Version**: 6.9.0
- **Docker Version**: Latest
- **Python Version**: 3.11 (inside container)

### Steps to Reproduce

please fix 

### Expected Behavior

please fix

### Actual Behavior

text
Traceback (most recent call last):
File "/app/recon/partial_recon.py", line 37, in <module>
from recon.partial_recon_modules.helpers import (
File "/app/recon/partial_recon_modules/init.py", line 10, in <module>
from .graph_builders import (
File "/app/recon/partial_recon_modules/graph_builders.py", line 11, in <module>
from graph_db import Neo4jClient
ImportError: cannot import name 'Neo4jClient' from 'graph_db' (unknown location)

### Troubleshooting Steps Already Taken
1. Verified that the `neo4j` python package (v6.2.0) is correctly installed inside the `redamon-recon` container.
2. Verified that `/app/graph_db/__init__.py` exists and contains `from .neo4j_client import Neo4jClient`.
3. Attempted to manually fix `graph_builders.py`, but noticed that during edits/rebuilds, the file sometimes loses its formatting (e.g., `Path(__file__)` becomes `Path(file)`, missing `#` on comments, and lost indentation), suggesting a potential fragile import path or file corruption during the build context transfer.
4. Ran `docker compose build --no-cache recon` multiple times to rule out caching issues.

### Expected Behavior
Partial recon should successfully import `Neo4jClient` and execute the requested tool (e.g., VHost & SNI) without crashing.

### Request
Could you please verify the canonical import path for `Neo4jClient` in `recon/partial_recon_modules/graph_builders.py` for v6.9.0? Alternatively, providing the raw, unmodified version of this file would help rule out any local file corruption.

### Logs

```shell

```

**Comment by samugit83** [comment]
Confirmed, and thanks for the detailed report. Fixed in **v6.9.1**. The import path in `graph_builders.py` was never the problem, so there's no file corruption to hunt down on your side.

**Root cause.** The orchestrator bind-mounts `graph_db` into every spawned scan container at `/app/graph_db`, on top of the copy already baked into the image. It worked out the host path by *deriving* it: take the path Docker reports for the `recon` mount, strip the last segment, append `graph_db`. On plain Linux Docker that guess is correct. On Docker Desktop with WSL2, Docker reports a rewritten bind `Source`, so the sibling guess names a path that exists nowhere.

A missing bind source is not an error to Docker. It silently auto-creates an empty directory and mounts that. The empty directory then shadows the good `graph_db` in the image, Python sees an empty namespace package, and you get exactly your error. The `(unknown location)` suffix is the giveaway: it means Python found the directory but no `__init__.py` inside it.

That also explains why full recon looked healthy. Every graph write in the full pipeline is wrapped in `try/except`, so a broken mount just stops writing to Neo4j in silence. Partial recon has no such net and hard-crashes. If you ran a full recon during this period, it very likely produced results without populating the graph.

**On your specific question:** in v6.9.0 there is no module-level `from graph_db import Neo4jClient` in `graph_builders.py`. Every `graph_db` import under `recon/partial_recon_modules/` is function-local, so line 11 of the shipped file is a `def`, not an import. Your traceback shows it at module level, which matches the manual edit you mention in step 3. That edit only moved *where* the error surfaced, from call time to import time; the underlying failure was identical. The formatting oddities you saw (`__file__` becoming `file`, `#` disappearing) are a markdown paste artifact rather than file corruption, which is also why your traceback shows `init.py` instead of `__init__.py`: GitHub renders the double underscores as bold.

**What to do:**

```bash
cd /path/to/redamon
./redamon.sh update
```

Then re-run VHost & SNI, or any partial tool. No image rebuild is needed for this fix. If the update stops because of the local edits you made to `graph_builders.py` while troubleshooting, revert that file and re-run.

**What changed in 6.9.1.** `graph_db`'s host path is now auto-detected from the orchestrator's own `./graph_db:/app/graph_db:ro` mount, the same way `RECON_PATH` and every other source path is already resolved, with a `GRAPH_DB_PATH` env override. When it cannot be detected the bind is skipped entirely rather than allowed to shadow the image's copy. Both entry points also preflight the mount now, so any future misconfiguration reports what is wrong and how to fix it instead of raising `cannot import name 'Neo4jClient'`.
